### 대체투자상품 자산군별 분류

| 자산군 | 종목명                      | 코드    | 기초지수                                    | 수수료(연) | 운용사           |
| ------ | --------------------------- | ------- | ------------------------------------------- | ---------- | ---------------- |
| 원자재 | KODEX WTI원유선물(H)        | A261220 | S&P GSCI Crude Oil Index ER                 | 0.35%      | 삼성자산운용     |
| 원자재 | KODEX 골드선물(H)           | A132030 | S&P GSCI Gold Index(TR)                     | 0.68%      | 삼성자산운용     |
| 원자재 | KODEX 은선물(H)             | A144600 | S&P GSCI Silver Index(TR)                   | 0.68%      | 삼성자산운용     |
| 원자재 | TIGER 원유선물Enhanced(H)   | A130680 | S&P GSCI Crude Oil Enhanced Index ER        | 0.69%      | 미래에셋자산운용 |
| 원자재 | TIGER 농산물선물Enhanced(H) | A137610 | S&P GSCI Agriculture Enhanced Index(ER)     | 0.69%      | 미래에셋자산운용 |
| 원자재 | KODEX 구리선물(H)           | A138910 | S&P GSCI North American Copper Index(TR)    | 0.68%      | 삼성자산운용     |
| 원자재 | KODEX 3대농산물선물(H)      | A271060 | S&P GSCI Grains Select Index ER             | 0.55%      | 삼성자산운용     |
| 원자재 | TIGER 구리실물              | A160580 | S&P GSCI Cash Copper Index                  | 0.83%      | 미래에셋자산운용 |
| 원자재 | KODEX 콩선물(H)             | A138920 | S&P GSCI Soybeans Index(TR)                 | 0.68%      | 삼성자산운용     |
| 원자재 | TIGER 금은선물(H)           | A139320 | S&P GSCI Precious Metals Index(TR)          | 0.69%      | 미래에셋자산운용 |
| 원자재 | KBSTAR 팔라듐선물(H)        | A334690 | S&P GSCI Palladium Excess Return Index      | 0.60%      | 케이비자산운용   |
| 원자재 | KODEX WTI원유선물인버스(H)  | A271050 | S&P GSCI Crude Oil Index ER                 | 0.35%      | 삼성자산운용     |
| 원자재 | TIGER 금속선물(H)           | A139310 | S&P GSCI Industrial Metals Select Index(TR) | 0.69%      | 미래에셋자산운용 |
| 원자재 | KBSTAR 팔라듐선물인버스(H)  | A334700 | S&P GSCI Palladium Excess Return Index      | 0.60%      | 케이비자산운용   |



| 자산군 | 종목명                               | 코드    | 기초지수                                                  | 수수료(연) | 운용사                 |
| ------ | ------------------------------------ | ------- | --------------------------------------------------------- | ---------- | ---------------------- |
| 채권   | KODEX 단기채권                       | A153130 | KRW Cash 지수(총수익)                                     | 0.15%      | 삼성자산운용           |
| 채권   | KODEX 종합채권(AA-이상)액티브        | A273130 | KAP 한국종합채권지수                                      | 0.07%      | 삼성자산운용           |
| 채권   | KODEX 단기채권PLUS                   | A214980 | KRW Cash PLUS 지수(총수익)                                | 0.15%      | 삼성자산운용           |
| 채권   | TIGER 단기통안채                     | A157450 | KIS 통안채 3개월(총수익)                                  | 0.09%      | 미래에셋자산운용       |
| 채권   | KOSEF 국고채10년                     | A148070 | KIS 10년 국고채 지수 (총수익)                             | 0.15%      | 키움투자자산운용       |
| 채권   | HANARO 단기통안채                    | A306540 | KAP 단기 통안채 지수(총수익)                              | 0.10%      | 엔에이치아문디자산운용 |
| 채권   | KBSTAR 단기통안채                    | A196230 | KIS 통안채 5개월 지수(총수익)                             | 0.13%      | 케이비자산운용         |
| 채권   | TIGER 단기채권액티브                 | A272580 | KIS 통안채 3개월(총수익)                                  | 0.07%      | 미래에셋자산운용       |
| 채권   | KINDEX 단기통안채                    | A190620 | KIS MSB 단기지수(총수익)                                  | 0.07%      | 한국투자신탁운용       |
| 채권   | KODEX 국채선물10년인버스             | A176950 | 10년국채선물지수                                          | 0.07%      | 삼성자산운용           |
| 채권   | KBSTAR 중기우량회사채                | A136340 | KOBI 크레딧 지수(총수익)                                  | 0.07%      | 케이비자산운용         |
| 채권   | KODEX 단기변동금리부채권액티브       | A273140 | KAP 단기변동금리부은행채권지수                            | 0.15%      | 삼성자산운용           |
| 채권   | KBSTAR 단기국공채액티브              | A272560 | KIS 종합채권국공채3M~1.5Y지수                             | 0.07%      | 케이비자산운용         |
| 채권   | KODEX 국고채3년                      | A114260 | MKF 국고채지수(총수익)                                    | 0.15%      | 삼성자산운용           |
| 채권   | TIGER 중장기국채                     | A302190 | KIS 국채 3-10년 지수(시장가격지수)                        | 0.15%      | 미래에셋자산운용       |
| 채권   | TIGER 국채3년                        | A114820 | KTB INDEX(시장가격)                                       | 0.15%      | 미래에셋자산운용       |
| 채권   | KBSTAR 금융채액티브                  | A336160 | KIS 종합채권금융채 2.5Y-3Y 지수 (총수익)                  | 0.07%      | 케이비자산운용         |
| 채권   | KOSEF 단기자금                       | A130730 | MK 머니마켓 지수(총수익)                                  | 0.15%      | 키움투자자산운용       |
| 채권   | TIGER 미국채10년선물                 | A305080 | S&P 10-Year U.S. Treasury Note Futures(ER)                | 0.29%      | 미래에셋자산운용       |
| 채권   | KOSEF 통안채1년                      | A122260 | MK 통안채지수(총수익)                                     | 0.15%      | 키움투자자산운용       |
| 채권   | KBSTAR 중장기국공채액티브            | A272570 | KIS 종합채권국공채4~5Y지수                                | 0.07%      | 케이비자산운용         |
| 채권   | KINDEX KIS종합채권(AA-이상)액티브    | A356540 | KIS 종합채권 AA-이상 총수익 지수(Total return Index)      | 0.07%      | 한국투자신탁운용       |
| 채권   | TIGER 미국달러단기채권액티브         | A329750 | KIS U.S. TREASURY BOND 0-1Y 지수(총수익)                  | 0.30%      | 미래에셋자산운용       |
| 채권   | KODEX 장기종합채권(AA-이상)액티브KAP | A363570 | KAP 한국장기종합채권지수(AA-이상, 총수익)                 | 0.07%      | 삼성자산운용           |
| 채권   | KINDEX 국고채3년                     | A114460 | KTB INDEX(시장가격)                                       | 0.15%      | 한국투자신탁운용       |
| 채권   | KBSTAR 국고채3년                     | A114100 | KTB INDEX(시장가격)                                       | 0.12%      | 케이비자산운용         |
| 채권   | KOSEF 국고채3년                      | A114470 | KTB INDEX(시장가격)                                       | 0.15%      | 키움투자자산운용       |
| 채권   | SMART KIS단기통안채                  | A363510 | KIS 단기통안채 Index(총수익)                              | 0.13%      | 신한자산운용           |
| 채권   | ARIRANG 미국장기우량회사채           | A332620 | ICE BofaAML 15+ Year AAA-A US Corporate Index(총수익지수) | 0.32%      | 한화자산운용           |
| 채권   | ARIRANG 단기채권액티브               | A278620 | KAP 투자적격 크레딧 채권 1년 지수(A- 이상,총수익)         | 0.13%      | 한화자산운용           |
| 채권   | TIGER 단기선진하이일드(합성 H)       | A182490 | Markit iBoxx USD Liquid High Yield 0-5 year 지수          | 0.24%      | 미래에셋자산운용       |
| 채권   | ARIRANG 미국단기우량회사채           | A332610 | ICE BofaAML 1-3 Year AAA-A US Corporate Index(총수익지수) | 0.32%      | 한화자산운용           |
| 채권   | KODEX 국채선물10년                   | A152380 | 10년국채선물지수                                          | 0.25%      | 삼성자산운용           |
| 채권   | KODEX 미국채울트라30년선물(H)        | A304660 | S&P Ultra T-Bond Futures Index(ER)                        | 0.30%      | 삼성자산운용           |
| 채권   | KINDEX 중장기국공채액티브            | A272910 | KIS 종합채권국공채1-10Y지수                               | 0.08%      | 한국투자신탁운용       |
| 채권   | KODEX 200미국채혼합                  | A284430 | 코스피 200 미국채 혼합지수                                | 0.35%      | 삼성자산운용           |
| 채권   | ARIRANG 우량회사채50 1년             | A239660 | KOBI HALF CREDIT Index(총수익)                            | 0.14%      | 한화자산운용           |
| 채권   | KODEX 미국채10년선물                 | A308620 | S&P 10-Year U.S. Treasury Note Futures KRW(ER)            | 0.30%      | 삼성자산운용           |
| 채권   | KOSEF 국고채10년레버리지             | A167860 | KIS 10년 국고채 지수 (총수익)                             | 0.30%      | 키움투자자산운용       |
| 채권   | ARIRANG 국채선물3년                  | A298340 | 국채선물지수                                              | 0.10%      | 한화자산운용           |
| 채권   | KINDEX 국고채10년                    | A365780 | KIS 10년 국고채 지수 (총수익)                             | 0.10%      | 한국투자신탁운용       |
| 채권   | HANARO KAP초장기국고채               | A346000 | KAP 초장기 국고채 지수(총수익)                            | 0.20%      | 엔에이치아문디자산운용 |
| 채권   | TIGER 국채선물3년인버스              | A302170 | 국채선물지수                                              | 0.07%      | 미래에셋자산운용       |
| 채권   | KBSTAR KRX국채선물3년10년스티프너2X  | A342600 | 국채선물 3년/10년 일드커브 스티프닝 지수(총수익지수)      | 0.20%      | 케이비자산운용         |
| 채권   | ARIRANG 국채선물10년                 | A289670 | 10년국채선물지수                                          | 0.13%      | 한화자산운용           |
| 채권   | KBSTAR KRX국채선물3년10년스티프너    | A342500 | 국채선물 3년/10년 일드커브 스티프닝 지수(총수익지수)      | 0.15%      | 케이비자산운용         |
| 채권   | 파워 중기국고채                      | A176710 | KTB INDEX(시장가격)                                       | 0.15%      | 교보악사자산운용       |
| 채권   | KBSTAR KRX국채선물3년10년플래트너    | A342610 | 국채선물 3년/10년 일드커브 플래트닝 지수(총수익지수)      | 0.15%      | 케이비자산운용         |
| 채권   | KBSTAR KRX국채선물3년10년플래트너2X  | A342620 | 국채선물 3년/10년 일드커브 플래트닝 지수(총수익지수)      | 0.20%      | 케이비자산운용         |
| 채권   | TIGER 국채선물10년인버스             | A302180 | 10년국채선물지수                                          | 0.07%      | 미래에셋자산운용       |
| 채권   | KBSTAR 국채선물10년인버스            | A295020 | 10년국채선물지수                                          | 0.07%      | 케이비자산운용         |
| 채권   | KODEX 국채선물3년인버스              | A292770 | 국채선물지수                                              | 0.07%      | 삼성자산운용           |
| 채권   | KINDEX 국채선물3년인버스             | A299080 | 국채선물지수                                              | 0.05%      | 한국투자신탁운용       |
| 채권   | KINDEX 국채선물10년인버스            | A299070 | 10년국채선물지수                                          | 0.05%      | 한국투자신탁운용       |
| 채권   | KBSTAR 국채선물10년                  | A295000 | 10년국채선물지수                                          | 0.07%      | 케이비자산운용         |



| 자산군 | 종목명                                  | 코드    | 기초지수                                                     | 수수료(연) | 운용사           |
| ------ | --------------------------------------- | ------- | ------------------------------------------------------------ | ---------- | ---------------- |
| 기타   | TIGER CD금리투자KIS(합성)               | A357870 | KIS CD Index(총수익)                                         | 0.15%      | 미래에셋자산운용 |
| 기타   | TIGER 미국MSCI리츠(합성 H)              | A182480 | MSCI US REIT Index                                           | 0.24%      | 미래에셋자산운용 |
| 기타   | KODEX 미국달러선물                      | A261240 | 미국달러선물지수                                             | 0.25%      | 삼성자산운용     |
| 기타   | KODEX 미국달러선물레버리지              | A261250 | 미국달러선물지수                                             | 0.45%      | 삼성자산운용     |
| 기타   | KOSEF 미국달러선물                      | A138230 | 미국달러선물지수                                             | 0.37%      | 키움투자자산운용 |
| 기타   | KODEX TRF3070                           | A329650 | FnGuide TRF 3070 지수                                        | 0.24%      | 삼성자산운용     |
| 기타   | KODEX 배당성장채권혼합                  | A237370 | 배당성장채권혼합지수                                         | 0.19%      | 삼성자산운용     |
| 기타   | TIGER KIS부동산인프라채권TR             | A341850 | KIS 부동산인프라채권 TR지수                                  | 0.22%      | 미래에셋자산운용 |
| 기타   | KBSTAR 채권혼합                         | A183700 | 주식국채혼합(채권형)지수                                     | 0.20%      | 케이비자산운용   |
| 기타   | TIGER 미국달러선물인버스2X              | A261120 | 미국달러선물지수                                             | 0.47%      | 미래에셋자산운용 |
| 기타   | KBSTAR 헬스케어채권혼합                 | A253290 | FnGuide 헬스케어 채권혼합 지수                               | 0.35%      | 케이비자산운용   |
| 기타   | KODEX TRF7030                           | A329670 | FnGuide TRF 7030 지수                                        | 0.10%      | 삼성자산운용     |
| 기타   | ARIRANG 고배당주채권혼합                | A251600 | FnGuide 고배당 채권혼합 지수                                 | 0.20%      | 한화자산운용     |
| 기타   | KODEX TRF5050                           | A329660 | FnGuide TRF 5050 지수                                        | 0.17%      | 삼성자산운용     |
| 기타   | KINDEX 싱가포르리츠                     | A316300 | Morningstar Singapore REIT Yield Focus Index(PR)             | 0.40%      | 한국투자신탁운용 |
| 기타   | KOSEF 미국달러선물인버스                | A139660 | 미국달러선물지수                                             | 0.49%      | 키움투자자산운용 |
| 기타   | KBSTAR 주식혼합                         | A183710 | 주식국채혼합(주식형)지수                                     | 0.25%      | 케이비자산운용   |
| 기타   | TIGER 경기방어채권혼합                  | A237440 | 경기방어소비재 채권혼합 지수                                 | 0.20%      | 미래에셋자산운용 |
| 기타   | KODEX 다우존스미국리츠(H)               | A352560 | Dow Jones U.S. Real Estate PR Index                          | 0.30%      | 삼성자산운용     |
| 기타   | KBSTAR V&S셀렉트밸류채권혼합            | A241390 | FnGuide 셀렉트벨류 채권혼합지수                              | 0.23%      | 케이비자산운용   |
| 기타   | KINDEX 모닝스타싱가포르리츠채권혼합     | A342140 | Morningstar Singapore REIT Yield Focus Income Protection Index | 0.40%      | 한국투자신탁운용 |
| 기타   | KODEX TSE일본리츠(H)                    | A352540 | Tokyo Stock Exchange REIT Index                              | 0.30%      | 삼성자산운용     |
| 기타   | TIGER 일본엔선물                        | A292560 | 엔선물지수                                                   | 0.25%      | 미래에셋자산운용 |
| 기타   | KBSTAR 미국고정배당우선증권ICE TR       | A354240 | ICE BofAML Core Plus Fixed Rate Preferred Securities Index   | 0.50%      | 케이비자산운용   |
| 기타   | KINDEX 미국다우존스리츠(합성 H)         | A181480 | Dow Jones U.S. Real Estate Index                             | 0.30%      | 한국투자신탁운용 |
| 기타   | KBSTAR 글로벌데이터센터리츠나스닥(합성) | A375270 | Benchmark Data & Infrastructure Real Estate SCTR Net Total Return  Index | 0.40%      | 케이비자산운용   |
| 기타   | TIGER 미국달러선물레버리지              | A261110 | 미국달러선물지수                                             | 0.47%      | 미래에셋자산운용 |
| 기타   | ARIRANG 스마트베타Quality채권혼합       | A238670 | WISE-KAP 스마트베타 Quality 채권혼합지수                     | 0.20%      | 한화자산운용     |
| 기타   | KODEX 미국달러선물인버스                | A261270 | 미국달러선물지수                                             | 0.45%      | 삼성자산운용     |
| 기타   | KODEX 미국달러선물인버스2X              | A261260 | 미국달러선물지수                                             | 0.45%      | 삼성자산운용     |
| 기타   | KODEX 멀티에셋하이인컴(H)               | A321410 | Morningstar Multi-Asset High Income 10% Capped Index         | 0.25%      | 삼성자산운용     |
| 기타   | TIGER 일본엔선물레버리지                | A292570 | 엔선물지수                                                   | 0.47%      | 미래에셋자산운용 |
| 기타   | TIGER 일본엔선물인버스                  | A292580 | 엔선물지수                                                   | 0.47%      | 미래에셋자산운용 |
| 기타   | TIGER 일본엔선물인버스2X                | A292590 | 엔선물지수                                                   | 0.47%      | 미래에셋자산운용 |